---
  - name: Gather EC2 Facts
    ec2_instance_facts:
      filters:
        "tag:Name": "visualserver"
    register: ec2_out

  - debug: 
      msg: "{{ ec2_out.instances[0].public_dns_name }}"

  - name: Add new instance to host group
    add_host:
      hostname: "{{ ec2_out.instances[0].public_dns_name }}"
      groupname: visualserver
      ansible_ssh_private_key_file:  "{{ec2_private_key_file}}"
      ansible_user: "ec2-user"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    with_items: 
      - "{{ ec2_out.instances }}"
      #- "{{ ec2_out.tagged_instances }}"